 first_name = input("Enter your first name: ")
    middle_name = input("Enter your middle name: ")
    last_name = input("Enter your last name: ")
    age = input("Enter your age: ")
    city = input("Enter your city: ")
    university = input("Enter your university: ")
    num_courses = input("Enter the number of courses you're taking: ")
    intermediate_percentage = input("Enter your intermediate percentage: ")
    address = input("Enter your address: ")
    print("\nPersonal Information:")
    print("First Name:", first_name)
    print("Middle Name:", middle_name)
    print("Last Name:", last_name)
    print("Age:", age)
    print("City:", city)
    print("University:", university)
    print("Number of Courses:", num_courses)
    print("Intermediate Percentage:", intermediate_percentage)
    print("Address:", address)